<script setup lang="ts">
//it appears that while vite created this import line for RouterLink and RouterView, it doesn't seem to be needed in order to access those components
// import { RouterLink, RouterView } from 'vue-router'

// import HelloWorld from './components/HelloWorld.vue'
import { useStore } from '@/store'
const store = useStore()
</script>

<template>
  <!-- The original Vite scaffolding template is being left in and commented out, so that it can be uncommented to switch back to it and experiment with it -->

  <!-- <header>
    <img alt="Vue logo" class="logo" src="@/assets/logo.svg" width="125" height="125" />

    <div class="wrapper">
      <HelloWorld msg="You did it!" />

      <nav>
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/about">About</RouterLink>
      </nav>
    </div>
  </header>

  <RouterView /> -->

  <!-- everything inside this inner div is the main app contents -->
  <header>
    <RouterLink to="/">
      <h1>Contact Interaction Notes and Followup Reminders</h1>
    </RouterLink>
    <nav>
      <div>
        <button class="nav-button">Show Contacts</button>
        <button class="nav-button" @click="store.addContact">Add Contact</button>
        <button class="nav-button" @click="store.addInteraction">Add Interaction</button>
        <RouterLink to="/interactions">
          <button class="nav-button">Show Interactions</button>
        </RouterLink>
      </div>
      <div>
        <button class="nav-button" @click="store.importData">Import Data</button>
        <button class="nav-button" @click="store.exportData">Export Data</button>
        <button class="nav-button" @click="store.clearData">Clear Data</button>
      </div>
    </nav>
  </header>
  <main class="router-view">
    <RouterView />
  </main>
</template>

<style scoped>
h1 {
  text-align: center;
  font-weight: 700;
  margin-bottom: 20px;
}

nav div {
  /* border: 1px black solid; */
  display: flex;
  /* justify-content: space-around; */
  align-items: center; /* this line exists for now because it keeps the buttons the same height whether wrapped in RouterLink or not*/
  justify-content: center;
  gap: 10px;
  width: 60%;
  margin: 16px auto;
}

.nav-button {
  border: 1px #333 solid;
  border-radius: 5px;
  padding: 4px 8px;
  background-color: #ddd;
  font-weight: 700;
}

.router-view {
  border: 1px black solid;
  margin: 20px auto;
  width: 100%;
  min-height: 300px;
}

/* The following CSS was originally generated by Vite for the scaffolding files */
/* header {
  line-height: 1.5;
  max-height: 100vh;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

nav {
  width: 100%;
  font-size: 12px;
  text-align: center;
  margin-top: 2rem;
}

nav a.router-link-exact-active {
  color: var(--color-text);
}

nav a.router-link-exact-active:hover {
  background-color: transparent;
}

nav a {
  display: inline-block;
  padding: 0 1rem;
  border-left: 1px solid var(--color-border);
}

nav a:first-of-type {
  border: 0;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }

  nav {
    text-align: left;
    margin-left: -1rem;
    font-size: 1rem;

    padding: 1rem 0;
    margin-top: 1rem;
  }
} */
</style>
