# hand made github actions workflow to build, test, and deploy to github pages

name: BuildTestDeploy

on:
  push:

jobs:
  build-deploy:
    name: 'build-deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:unit

      - name: 'Deploy to GitHub Pages'
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
#  test:
#    runs-on: ubuntu-latest
#    needs: build

#    steps:
#      - run: npm run test:unit
# still needs the part where it deploys to github pages
# I feel like build and test might as well just both be one single job
