# hand made github actions workflow to build, test, and deploy to github pages

name: BuildTestDeploy

on:
  push:

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build --if-present

  test:
    needs: build

    steps:
      - run: npm run test:unit
# still needs the part where it deploys to github pages
